apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: testhl
data:
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-np
  namespace: testhl
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
    - port: 8761
      nodePort: 30030
      name: eureka
  selector:
    app: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: testhl
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: testhl
spec:
  serviceName: 'eureka'
  # n instances
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: bitinit/eureka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1200Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: ENVIRONMENT
              value: "prod"
            - name: JVM_OPTS
              value: "-Xms1g -Xmx1g"
